batch_size: 8
epochs: 5

amp_cfg:
  use_amp: False
  enable: False
  level: O1
  scaler:
    init_loss_scaling: 32.0

train_dataset:
  type: ApolloPCDataset
  dataset_root: datasets/
  dataset_list: ['apolloscape']
  transforms:
    - type: LoadPointCloud
      dim: 5
      use_dim: 4
      sep: ''
    - type: SamplingDatabaseV2
      min_num_points_in_box_per_class:
        smallMot: 20
        bigMot: 20
        nonMot: 10
        pedestrian: 8
        TrafficCone: 8
      max_num_samples_per_class:
        smallMot: 10
        bigMot: 10
        nonMot: 10
        pedestrian: 10
        TrafficCone: 10
      ignored_difficulty: [-1]
      database_anno_list: ['apolloscape']
      database_root: datasets/
      class_names: ['smallMot', 'bigMot', 'nonMot', 'pedestrian', 'TrafficCone']
    # - type: RandomObjectPerturb
    #  rotation_range: [-0.15707963267, 0.15707963267]
    #   translation_std: [0.25, 0.25, 0.25]
    #   max_num_attempts: 100
    - type: FilterSmallBBox
      size_thr: [0.01, 0.01, 0.01]
    - type: RandomVerticalFlip
    - type: RandomHorizontalFlip
    - type: GlobalRotate
      min_rot: -0.78539816
      max_rot: 0.78539816
    - type: GlobalScale
      min_scale: 0.9
      max_scale: 1.1
    - type: GlobalTranslate
      translation_std: [0.5, 0.5, 0.5]
    - type: ShufflePoint
    - type: FilterPointOutsideRange
      point_cloud_range: [-51.2, -51.2, -5.0, 51.2, 51.2, 3.0]
    - type: FilterBBoxOutsideRange
      point_cloud_range: [-51.2, -51.2, -5.0, 51.2, 51.2, 3.0]
    - type: Gt2CenterPointTarget
      tasks:  # *
        - num_class: 1
          class_names: ["smallMot"]
        - num_class: 1
          class_names: ["bigMot"]
        - num_class: 1
          class_names: ['nonMot']
        - num_class: 1
          class_names: ['pedestrian']
        - num_class: 1
          class_names: ['TrafficCone']
      down_ratio: 4
      point_cloud_range: [-51.2, -51.2, -5.0, 51.2, 51.2, 3.0]
      voxel_size: [0.20, 0.20, 8]
      gaussian_overlap: 0.1
      max_objs: 500
      min_radius: 2
  mode: train
  class_balanced_sampling: False
  class_names: ['smallMot', 'bigMot', 'nonMot', 'pedestrian', 'TrafficCone']

val_dataset:
  type: ApolloPCDataset
  dataset_root: datasets
  dataset_list: ['apolloscape']
  transforms:
    - type: LoadPointCloud
      dim: 5
      use_dim: 4
      sep: ''
    - type: FilterPointOutsideRange
      point_cloud_range: [-51.2, -51.2, -5.0, 51.2, 51.2, 3.0]
  mode: val
  class_names: ['smallMot', 'bigMot', 'nonMot', 'pedestrian', 'TrafficCone']
  eval_class_map: {'smallMot': 'smallMot', 'bigMot': 'bigMot', 'nonMot': 'nonMot', 'Tricyclist': 'nonMot', 'pedestrian': 'pedestrian', 'TrafficCone': 'TrafficCone'}
  distance_threshold: 51.2

optimizer:
  type: OneCycleAdam
  beta2: 0.99
  weight_decay: 0.01
  grad_clip:
    type: ClipGradByGlobalNorm
    clip_norm: 35
  beta1:
    type: OneCycleDecayWarmupMomentum
    momentum_peak: 0.95
    momentum_trough: 0.85
    step_ratio_peak: 0.4

lr_scheduler:
  type: OneCycleWarmupDecayLr
  base_learning_rate: 0.0001
  lr_ratio_peak: 10
  lr_ratio_trough: 0.0001
  step_ratio_peak: 0.4

model:
  type: CenterPoint
  voxelizer:
    type: HardVoxelizer
    point_cloud_range: [-51.2, -51.2, -5.0, 51.2, 51.2, 3.0]
    voxel_size: [0.20, 0.20, 8]
    max_num_points_in_voxel: 20
    max_num_voxels: [30000, 60000]
  voxel_encoder:
    type: PillarFeatureNet
    in_channels: 4
    feat_channels: [64, 64]
    with_distance: False
    max_num_points_in_voxel: 20
    voxel_size: [0.20, 0.20, 8]
    point_cloud_range: [-51.2, -51.2, -5.0, 51.2, 51.2, 3.0]
    legacy: False
  middle_encoder:
    type: PointPillarsScatter
    in_channels: 64
    voxel_size: [0.20, 0.20, 8]
    point_cloud_range: [-51.2, -51.2, -5.0, 51.2, 51.2, 3.0]
  backbone:
    type: SecondBackbone
    in_channels: 64
    out_channels: [64, 128, 256]
    layer_nums: [3, 5, 5]
    downsample_strides: [2, 2, 2]
  neck:
    type: SecondFPN
    in_channels: [64, 128, 256]
    out_channels: [128, 128, 128]
    upsample_strides: [0.5, 1, 2]
    use_conv_for_no_stride: True
  bbox_head:
    type: CenterHead
    in_channels: 384
    tasks:
        - num_class: 1
          class_names: ["smallMot"]
        - num_class: 1
          class_names: ["bigMot"]
        - num_class: 1
          class_names: ['nonMot']
        - num_class: 1
          class_names: ['pedestrian']
        - num_class: 1
          class_names: ['TrafficCone']
    weight: 0.25
    code_weights: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0] # [x, y, z, w, h, l, sin(angle), cos(angle)] weight in loc loss
    common_heads:
      reg: [2, 2]
      height: [1, 2]
      dim: [3, 2]
      rot: [2, 2]
  test_cfg:
    post_center_limit_range: [-90., -90., -10., 90., 90., 10.]
    nms:
      nms_pre_max_size: 1000
      nms_post_max_size: 83
      nms_iou_threshold: 0.2
    score_threshold: 0.5
    point_cloud_range: [-51.2, -51.2, -5.0, 51.2, 51.2, 3.0]
    down_ratio: 4
    voxel_size: [0.20, 0.20, 8]